server:
  port: 8083
spring:
  application:
    name: ms-transaction
  cloud:
    aws:
      region:
        static: us-east-1

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/ms-transactions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

client:
  url: http://host.docker.internal:8082/api/v1/accounts

config:
  url-docker-localstack: http://host.docker.internal:4566

sns:
  topic-arn-transaction: arn:aws:sns:us-east-1:000000000000:transactions