server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health ,info,metrics
spring:
  application:
    name: ms-clients
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: "cbgomes"
        secret-key: "gbgomes"
      dynamodb:
        endpoint: http://localhost:4566