services:
  postgres:
    image: postgres:17.5
    container_name: bootcamp-acme-bank
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network
  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: carlos@viaresults.com.br
      PGADMIN_DEFAULT_PASSWORD: cbgomes
    ports:
      - 8888:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network
  ms-clients:
    build:
      context: ..
      dockerfile: ../ms-clients/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - local-network
  ms-accounts:
    build:
      context: ..
      dockerfile: ../ms-accounts/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - local-network
  ms-transactions:
    build:
      context: ..
      dockerfile: ../ms-transactions/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - local-network
volumes:
  postgres-data:
  pgadmin-data:

networks:
  local-network:
    driver: bridge