services:
  postgres:
    image: postgres:17.5
    container_name: bootcamp-acme-bank
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: carlos@viaresults.com.br
      PGADMIN_DEFAULT_PASSWORD: cbgomes
    ports:
      - 8888:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network
volumes:
  postgres-data:
  pgadmin-data:

networks:
  local-network:
    driver: bridge