server:
  port: 8081

spring:
  application:
    name: ms-clients

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: "cbgomes"
        secret-key: "gbgomes"
      dynamodb:
        endpoint: http://host.docker.internal:4566