server:
  port: 8082
spring:
  application:
    name: ms-account
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: "cbgomes"
        secret-key: "gbgomes"
      dynamodb:
        endpoint: http://host.docker.internal:4566
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/ms-accounts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

client:
  url: http://host.docker.internal:8081/api/v1/clients
